version: '3.8'

services:
  # MongoDB Veritabanı
  mongodb:
    image: mongo:7.0
    container_name: hometeam-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: homeTeam2025!
      MONGO_INITDB_DATABASE: hometeam
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - hometeam-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: hometeam-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hometeam-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hometeam-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://admin:homeTeam2025!@mongodb:27017/hometeam?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-development
      JWT_EXPIRES_IN: 7d
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - hometeam-network

  # MongoDB Express (Geliştirme için)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: hometeam-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: homeTeam2025!
      ME_CONFIG_MONGODB_URL: mongodb://admin:homeTeam2025!@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: homeTeam2025!
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - hometeam-network

  # Redis Commander (Geliştirme için)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: hometeam-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    networks:
      - hometeam-network

# Persistent volumes
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

# Network configuration
networks:
  hometeam-network:
    driver: bridge
